version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: traffic-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - traffic_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: traffic-frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BACKEND_URL=http://backend:8000
    networks:
      - traffic_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: traffic-backend
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/output
      - ./logs:/app/logs
    networks:
      - traffic_network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: traffic-mysql
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: traffic-redis
    env_file:
      - .env
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  traffic_network:
    driver: bridge
